BEO-Timing: LogfileLesenDialog Class Reference
LogfileLesenDialog Class Reference
Dieser Dialog sucht eine Log-Datei einer Zielstation nach nicht uebermittelten Eintraegen ab.
#include <logfilelesendialog.h>
Public Member Functions
LogfileLesenDialog (QWidget *parent=0)
Konstruktor.
~LogfileLesenDialog ()
Destruktor.
Private Types
enum streckentypen {
Rennvelo = 1, Mountainbike = 2, Laufen = 3, Walking = 4,
Langlauf = 5, Inline = 6
}
Private Slots
void on_okButton_released ()
Slot für den Ok-Button.
void on_canButton_released ()
Slot für den Abbrechen-Button.
void on_neuCheckBox_stateChanged (int state)
Slot für die Reaktion auf Änderungen der CheckBox.
void on_delCheckBox_stateChanged (int state)
Slot für die Reaktion auf Änderungen der CheckBox.
Private Member Functions
QListWidgetItem * createItem (QString line)
Inhalt der Listen erstellen.
Private Attributes
Ui::LogfileLesenDialogClass ui
QStringList add
QStringList remove
Detailed Description
Dieser Dialog sucht eine Log-Datei einer Zielstation nach nicht uebermittelten Eintraegen ab.
Definition at line 41 of file logfilelesendialog.h.
Member Enumeration Documentation
enum LogfileLesenDialog::streckentypen [private]
Enumerator:
Rennvelo
Mountainbike
Laufen
Walking
Langlauf
Inline
Definition at line 51 of file logfilelesendialog.h.
Constructor & Destructor Documentation
LogfileLesenDialog::LogfileLesenDialog (QWidget * parent = 0)
Konstruktor.
Definition at line 38 of file logfilelesendialog.cpp.
References createItem(), Ui_LogfileLesenDialogClass::delListWidget, Ui_LogfileLesenDialogClass::neuListWidget, Ui_LogfileLesenDialogClass::setupUi(), and ui.
LogfileLesenDialog::~LogfileLesenDialog ()
Destruktor.
Definition at line 129 of file logfilelesendialog.cpp.
Member Function Documentation
QListWidgetItem * LogfileLesenDialog::createItem (QString line) [private]
Inhalt der Listen erstellen.
Parameters:
line String aus der Logdatei
Returns:
Listenelement
Definition at line 139 of file logfilelesendialog.cpp.
References Inline, Langlauf, Laufen, Mountainbike, Rennvelo, and Walking.
Referenced by LogfileLesenDialog().
void LogfileLesenDialog::on_okButton_released () [private, slot]
Slot für den Ok-Button.
Definition at line 200 of file logfilelesendialog.cpp.
References Ui_LogfileLesenDialogClass::delListWidget, Ui_LogfileLesenDialogClass::neuListWidget, and ui.
void LogfileLesenDialog::on_canButton_released () [private, slot]
Slot für den Abbrechen-Button.
Definition at line 301 of file logfilelesendialog.cpp.
void LogfileLesenDialog::on_neuCheckBox_stateChanged (int state) [private, slot]
Slot für die Reaktion auf Änderungen der CheckBox.
Parameters:
state Status der CheckBox
Definition at line 177 of file logfilelesendialog.cpp.
References Ui_LogfileLesenDialogClass::neuListWidget, and ui.
void LogfileLesenDialog::on_delCheckBox_stateChanged (int state) [private, slot]
Slot für die Reaktion auf Änderungen der CheckBox.
Parameters:
state Status der CheckBox
Definition at line 189 of file logfilelesendialog.cpp.
References Ui_LogfileLesenDialogClass::delListWidget, and ui.
Member Data Documentation
Ui::LogfileLesenDialogClass LogfileLesenDialog::ui [private]
Definition at line 52 of file logfilelesendialog.h.
Referenced by LogfileLesenDialog(), on_delCheckBox_stateChanged(), on_neuCheckBox_stateChanged(), and on_okButton_released().
QStringList LogfileLesenDialog::add [private]
Definition at line 53 of file logfilelesendialog.h.
QStringList LogfileLesenDialog::remove [private]
Definition at line 54 of file logfilelesendialog.h.
The documentation for this class was generated from the following files:
logfilelesendialog.h
logfilelesendialog.cpp