BEO-Timing: NeuerUserDialog Class Reference
NeuerUserDialog Class Reference
Dieser Dialog dient zum erstellen eines neuen Benutzers.
#include <neueruserdialog.h>
Public Member Functions
NeuerUserDialog (User *user, QWidget *parent=0)
Konstruktor.
~NeuerUserDialog ()
Destruktor.
Private Types
enum streckentypen {
Rennvelo = 1, Mountainbike = 2, Laufen = 3, Walking = 4,
Langlauf = 5, Inline = 6
}
Private Slots
void on_okButton_released ()
Slot für OK-Button.
void on_canButton_released ()
Slot für Abbrechen-Button.
Private Member Functions
bool validation ()
Validierung der Einträge.
Private Attributes
Ui::NeuerUserDialogClass ui
User * pUser
int usertype_offset
Detailed Description
Dieser Dialog dient zum erstellen eines neuen Benutzers.
Definition at line 40 of file neueruserdialog.h.
Member Enumeration Documentation
enum NeuerUserDialog::streckentypen [private]
Enumerator:
Rennvelo
Mountainbike
Laufen
Walking
Langlauf
Inline
Definition at line 49 of file neueruserdialog.h.
Constructor & Destructor Documentation
NeuerUserDialog::NeuerUserDialog (User * user, QWidget * parent = 0)
Konstruktor.
Parameters:
user Pointer auf den angemeldeten Benutzer
parent Pointer auf das aufrufende Objekt
Definition at line 42 of file neueruserdialog.cpp.
References User::administrator, Ui_NeuerUserDialogClass::emailLineEdit, User::getRaceAuthority(), User::getUsertype(), Inline, Langlauf, Laufen, User::manager, Mountainbike, Ui_NeuerUserDialogClass::nameLineEdit, pUser, Rennvelo, Ui_NeuerUserDialogClass::setupUi(), Ui_NeuerUserDialogClass::streckenTreeWidget, Ui_NeuerUserDialogClass::typComboBox, ui, Ui_NeuerUserDialogClass::usernameLineEdit, User::usertype, usertype_offset, and Walking.
NeuerUserDialog::~NeuerUserDialog ()
Destruktor.
Definition at line 165 of file neueruserdialog.cpp.
Member Function Documentation
bool NeuerUserDialog::validation () [private]
Validierung der Einträge.
Definition at line 253 of file neueruserdialog.cpp.
References Ui_NeuerUserDialogClass::emailLineEdit, Ui_NeuerUserDialogClass::nameLineEdit, Ui_NeuerUserDialogClass::pwdLineEdit, Ui_NeuerUserDialogClass::pwdwLineEdit, ui, and Ui_NeuerUserDialogClass::usernameLineEdit.
Referenced by on_okButton_released().
void NeuerUserDialog::on_okButton_released () [private, slot]
Slot für OK-Button.
Definition at line 173 of file neueruserdialog.cpp.
References Ui_NeuerUserDialogClass::emailLineEdit, md5_buffer(), Ui_NeuerUserDialogClass::nameLineEdit, User::password, pUser, Ui_NeuerUserDialogClass::pwdLineEdit, Ui_NeuerUserDialogClass::pwdwLineEdit, Ui_NeuerUserDialogClass::streckenTreeWidget, Ui_NeuerUserDialogClass::typComboBox, ui, Ui_NeuerUserDialogClass::usernameLineEdit, usertype_offset, and validation().
void NeuerUserDialog::on_canButton_released () [private, slot]
Slot für Abbrechen-Button.
Definition at line 245 of file neueruserdialog.cpp.
Member Data Documentation
Ui::NeuerUserDialogClass NeuerUserDialog::ui [private]
Definition at line 51 of file neueruserdialog.h.
Referenced by NeuerUserDialog(), on_okButton_released(), and validation().
User* NeuerUserDialog::pUser [private]
Definition at line 52 of file neueruserdialog.h.
Referenced by NeuerUserDialog(), and on_okButton_released().
int NeuerUserDialog::usertype_offset [private]
Definition at line 53 of file neueruserdialog.h.
Referenced by NeuerUserDialog(), and on_okButton_released().
The documentation for this class was generated from the following files:
neueruserdialog.h
neueruserdialog.cpp