BEO-Timing: RFID_Thread Class Reference
RFID_Thread Class Reference
Erstellt einen Thread, welcher alle 0.5 Sekunden prüft ob eine Karte im Feld des Lesers erscheint.
#include <rfidThread.h>
Public Types
enum _state { running, stopp, pause, restart }
typedef enum RFID_Thread::_state STATE
Signals
void checkRFID ()
Public Member Functions
RFID_Thread (RFID_CR500 *pRfid)
Konstruktor.
~RFID_Thread ()
Destruktor.
void stop ()
Stoppen des Threads.
void setState (STATE state)
Setter für den State.
void setRFID (RFID_CR500 *pRfid)
Setzen des Pointers auf den Leser.
Protected Member Functions
void run ()
run-Funktion des Threads
Private Attributes
volatile bool stopped
volatile STATE state
RFID_CR500 * pRfid
Detailed Description
Erstellt einen Thread, welcher alle 0.5 Sekunden prüft ob eine Karte im Feld des Lesers erscheint.
Definition at line 45 of file rfidThread.h.
Member Typedef Documentation
typedef enum RFID_Thread::_state RFID_Thread::STATE
Member Enumeration Documentation
enum RFID_Thread::_state
Enumerator:
running
stopp
pause
restart
Definition at line 54 of file rfidThread.h.
Constructor & Destructor Documentation
RFID_Thread::RFID_Thread (RFID_CR500 * pRfid)
Konstruktor.
Parameters:
pRfid Pointer auf den RFID-Leser
Definition at line 41 of file rfidThread.cpp.
References stopped.
RFID_Thread::~RFID_Thread ()
Destruktor.
Definition at line 49 of file rfidThread.cpp.
Member Function Documentation
void RFID_Thread::stop ()
Stoppen des Threads.
Definition at line 62 of file rfidThread.cpp.
References stopped.
Referenced by BEO_Timing::~BEO_Timing().
void RFID_Thread::setState (STATE state)
Setter für den State.
Definition at line 56 of file rfidThread.cpp.
Referenced by BEO_Timing::CR500_verbinden(), and BEO_Timing::rfidConnection().
void RFID_Thread::setRFID (RFID_CR500 * pRfid)
Setzen des Pointers auf den Leser.
Definition at line 68 of file rfidThread.cpp.
Referenced by BEO_Timing::CR500_verbinden(), and BEO_Timing::rfidConnection().
void RFID_Thread::run () [protected]
run-Funktion des Threads
Definition at line 74 of file rfidThread.cpp.
References checkRFID(), pause, restart, RFID_REFRESH_RATE_ms, running, state, stopp, and stopped.
void RFID_Thread::checkRFID () [signal]
Definition at line 73 of file moc_rfidThread.cpp.
Referenced by run().
Member Data Documentation
volatile bool RFID_Thread::stopped [private]
Definition at line 60 of file rfidThread.h.
Referenced by RFID_Thread(), run(), and stop().
volatile STATE RFID_Thread::state [private]
Definition at line 61 of file rfidThread.h.
Referenced by run().
RFID_CR500* RFID_Thread::pRfid [private]
Definition at line 62 of file rfidThread.h.
The documentation for this class was generated from the following files:
RFID_Reader/rfidThread.h
debug/moc_rfidThread.cpp
RFID_Reader/rfidThread.cpp