BEO-Timing: NeuesRennenDialog Class Reference
NeuesRennenDialog Class Reference
Dieser Dialog dient zum erstellen eines neunen Rennens.
#include <neuesrennendialog.h>
Signals
void tree_update ()
Public Member Functions
NeuesRennenDialog (QWidget *parent=0)
Konstruktor.
~NeuesRennenDialog ()
Destruktor.
Private Types
enum streckentypen {
Rennvelo = 1, Mountainbike = 2, Laufen = 3, Walking = 4,
Langlauf = 5, Inline = 6
}
Private Slots
void on_okButton_released ()
Slot f端r Ok-Button.
void on_canButton_released ()
Slot f端r Abbrechen-Button.
Private Member Functions
bool validation ()
Valisierung der Eingaben.
Private Attributes
Ui::NeuesRennenDialogClass ui
Detailed Description
Dieser Dialog dient zum erstellen eines neunen Rennens.
Definition at line 40 of file neuesrennendialog.h.
Member Enumeration Documentation
enum NeuesRennenDialog::streckentypen [private]
Enumerator:
Rennvelo
Mountainbike
Laufen
Walking
Langlauf
Inline
Definition at line 50 of file neuesrennendialog.h.
Constructor & Destructor Documentation
NeuesRennenDialog::NeuesRennenDialog (QWidget * parent = 0)
Konstruktor.
Definition at line 38 of file neuesrennendialog.cpp.
References Ui_NeuesRennenDialogClass::enddatumDateEdit, Inline, Langlauf, Laufen, Mountainbike, Ui_NeuesRennenDialogClass::nameLineEdit, Rennvelo, Ui_NeuesRennenDialogClass::setupUi(), Ui_NeuesRennenDialogClass::startdatumDateEdit, Ui_NeuesRennenDialogClass::streckentypComboBox, ui, and Walking.
NeuesRennenDialog::~NeuesRennenDialog ()
Destruktor.
Definition at line 78 of file neuesrennendialog.cpp.
Member Function Documentation
bool NeuesRennenDialog::validation () [private]
Valisierung der Eingaben.
Definition at line 131 of file neuesrennendialog.cpp.
References Ui_NeuesRennenDialogClass::enddatumDateEdit, Ui_NeuesRennenDialogClass::nameLineEdit, Ui_NeuesRennenDialogClass::startdatumDateEdit, and ui.
Referenced by on_okButton_released().
void NeuesRennenDialog::on_okButton_released () [private, slot]
Slot f端r Ok-Button.
Definition at line 86 of file neuesrennendialog.cpp.
References Ui_NeuesRennenDialogClass::beschreibungTextEdit, Ui_NeuesRennenDialogClass::enddatumDateEdit, Ui_NeuesRennenDialogClass::nameLineEdit, Ui_NeuesRennenDialogClass::startdatumDateEdit, Ui_NeuesRennenDialogClass::streckentypComboBox, tree_update(), ui, and validation().
void NeuesRennenDialog::on_canButton_released () [private, slot]
Slot f端r Abbrechen-Button.
Definition at line 124 of file neuesrennendialog.cpp.
void NeuesRennenDialog::tree_update () [signal]
Definition at line 80 of file moc_neuesrennendialog.cpp.
Referenced by on_okButton_released().
Member Data Documentation
Ui::NeuesRennenDialogClass NeuesRennenDialog::ui [private]
Definition at line 51 of file neuesrennendialog.h.
Referenced by NeuesRennenDialog(), on_okButton_released(), and validation().
The documentation for this class was generated from the following files:
neuesrennendialog.h
debug/moc_neuesrennendialog.cpp
neuesrennendialog.cpp