BEO-Timing: PasswordChangeDialog Class Reference
PasswordChangeDialog Class Reference
Dieser Dialog dient zum aendern des Passworts des angemeldeten Benutzers.
#include <passwordchangedialog.h>
Signals
void valueCalculated (int value)
Public Member Functions
PasswordChangeDialog (User *pUser, QWidget *parent=0)
Konstruktor.
~PasswordChangeDialog ()
Destruktor.
Private Slots
void on_okButton_released ()
Slot für Ok-Button.
void on_canButton_released ()
Slot für den Abbrechen-Button.
void on_newLineEdit_textChanged (const QString &text)
Slot für die Änderungen im Texteingabefeld.
Private Member Functions
bool validation (QString pwd)
Validierung der Einträge.
Private Attributes
Ui::PasswordChangeDialogClass ui
User * pUser
Detailed Description
Dieser Dialog dient zum aendern des Passworts des angemeldeten Benutzers.
Definition at line 42 of file passwordchangedialog.h.
Constructor & Destructor Documentation
PasswordChangeDialog::PasswordChangeDialog (User * pUser, QWidget * parent = 0)
Konstruktor.
Parameters:
pUser Pointer auf den angemeldeten Benutzer
parent Pointer auf das aufrufende Objekt
Definition at line 42 of file passwordchangedialog.cpp.
References Ui_PasswordChangeDialogClass::setupUi(), Ui_PasswordChangeDialogClass::staerkeProgressBar, and ui.
PasswordChangeDialog::~PasswordChangeDialog ()
Destruktor.
Definition at line 56 of file passwordchangedialog.cpp.
Member Function Documentation
bool PasswordChangeDialog::validation (QString pwd) [private]
Validierung der Einträge.
Parameters:
pwd Neues Passwort
Definition at line 103 of file passwordchangedialog.cpp.
void PasswordChangeDialog::on_okButton_released () [private, slot]
Slot für Ok-Button.
Definition at line 64 of file passwordchangedialog.cpp.
References md5_buffer(), Ui_PasswordChangeDialogClass::newLineEdit, Ui_PasswordChangeDialogClass::oldLineEdit, User::password, pUser, ui, User::username, and Ui_PasswordChangeDialogClass::wiederLineEdit.
void PasswordChangeDialog::on_canButton_released () [private, slot]
Slot für den Abbrechen-Button.
Definition at line 96 of file passwordchangedialog.cpp.
void PasswordChangeDialog::on_newLineEdit_textChanged (const QString & text) [private, slot]
Slot für die Änderungen im Texteingabefeld.
Parameters:
text aktueller Text im Feld
Definition at line 118 of file passwordchangedialog.cpp.
References int(), Ui_PasswordChangeDialogClass::staerkeProgressBar, ui, and value.
void PasswordChangeDialog::valueCalculated (int value) [signal]
Definition at line 84 of file moc_passwordchangedialog.cpp.
Member Data Documentation
Ui::PasswordChangeDialogClass PasswordChangeDialog::ui [private]
Definition at line 52 of file passwordchangedialog.h.
Referenced by on_newLineEdit_textChanged(), on_okButton_released(), and PasswordChangeDialog().
User* PasswordChangeDialog::pUser [private]
Definition at line 53 of file passwordchangedialog.h.
Referenced by on_okButton_released().
The documentation for this class was generated from the following files:
passwordchangedialog.h
debug/moc_passwordchangedialog.cpp
passwordchangedialog.cpp