BEO-Timing: RechteAnpassen Class Reference
RechteAnpassen Class Reference
Dieser Dialog dient zum anpassen der Rechte eines beliebigen Benutzers.
#include <rechteanpassen.h>
Public Member Functions
RechteAnpassen (User *user, QWidget *parent=0)
Slot für die Reaktion auf Änderungen der CheckBox.
~RechteAnpassen ()
Destruktor.
Private Types
enum streckentypen {
Rennvelo = 1, Mountainbike = 2, Laufen = 3, Walking = 4,
Langlauf = 5, Inline = 6
}
Private Slots
void on_comboBox_currentIndexChanged (const QString &text)
Slot für die Änderungen der Selektion der ComboBox.
void on_okButton_released ()
Slot für OK-Button.
void on_canButton_released ()
Slot für Abbrechen-Button.
Private Attributes
Ui::RechteAnpassenClass ui
User * pUser
User * pChangeUser
Detailed Description
Dieser Dialog dient zum anpassen der Rechte eines beliebigen Benutzers.
Definition at line 42 of file rechteanpassen.h.
Member Enumeration Documentation
enum RechteAnpassen::streckentypen [private]
Enumerator:
Rennvelo
Mountainbike
Laufen
Walking
Langlauf
Inline
Definition at line 51 of file rechteanpassen.h.
Constructor & Destructor Documentation
RechteAnpassen::RechteAnpassen (User * user, QWidget * parent = 0)
Slot für die Reaktion auf Änderungen der CheckBox.
Parameters:
user Pointer auf den angemeldeten Benutzer
parent Pointer auf das aufrufende Objekt
Definition at line 40 of file rechteanpassen.cpp.
References Ui_RechteAnpassenClass::comboBox, User::getRaceAuthority(), Inline, Langlauf, Laufen, Mountainbike, pUser, Rennvelo, Ui_RechteAnpassenClass::setupUi(), Ui_RechteAnpassenClass::streckenTreeWidget, ui, and Walking.
RechteAnpassen::~RechteAnpassen ()
Destruktor.
Definition at line 135 of file rechteanpassen.cpp.
Member Function Documentation
void RechteAnpassen::on_comboBox_currentIndexChanged (const QString & text) [private, slot]
Slot für die Änderungen der Selektion der ComboBox.
Parameters:
text Referenz auf den gewählten Text
Definition at line 143 of file rechteanpassen.cpp.
References Ui_RechteAnpassenClass::altCheckBox, and ui.
void RechteAnpassen::on_okButton_released () [private, slot]
Slot für OK-Button.
Definition at line 150 of file rechteanpassen.cpp.
References Ui_RechteAnpassenClass::altCheckBox, Ui_RechteAnpassenClass::comboBox, User::Init(), md5_buffer(), User::password, pChangeUser, pUser, User::rennen, Ui_RechteAnpassenClass::streckenTreeWidget, and ui.
void RechteAnpassen::on_canButton_released () [private, slot]
Slot für Abbrechen-Button.
Definition at line 200 of file rechteanpassen.cpp.
Member Data Documentation
Ui::RechteAnpassenClass RechteAnpassen::ui [private]
Definition at line 52 of file rechteanpassen.h.
Referenced by on_comboBox_currentIndexChanged(), on_okButton_released(), and RechteAnpassen().
User* RechteAnpassen::pUser [private]
Definition at line 53 of file rechteanpassen.h.
Referenced by on_okButton_released(), and RechteAnpassen().
User* RechteAnpassen::pChangeUser [private]
Definition at line 54 of file rechteanpassen.h.
Referenced by on_okButton_released().
The documentation for this class was generated from the following files:
rechteanpassen.h
rechteanpassen.cpp