BEO-Timing: User Class Reference
User Class Reference
Diese Klasse symbolisiert einen Benutzer und stellt Funktionen bereit.
#include <User.h>
Public Types
enum { superadministrator, administrator, manager, user }
Public Member Functions
User ()
Konstruktor.
virtual ~User ()
Destruktor.
int getUsertype ()
Gibt den Usertype zurück.
void Init (QString username, QString password) throw (QString)
Initialisierung des Benutzers. Diese Methode wirft eine Exception, im Falle eines falschen Benutzernames oder Passworts.
void Init (QString username)
Initialisieren über den Benutzernamen.
bool checkPassword (QString password)
bool getRaceAuthority (int race)
Prüfen, ob der Benutzer die Berechtigung für ein Rennen hat.
bool getLogonSuccess ()
LogonSuccess überprüfen.
Protected Attributes
QString username
QString name
QString email
QString password
int usertype
QString rennen
bool logonSuccess
Friends
class PasswordChangeDialog
class NeuerUserDialog
class RechteAnpassen
Detailed Description
Diese Klasse symbolisiert einen Benutzer und stellt Funktionen bereit.
Definition at line 40 of file User.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
superadministrator
administrator
manager
user
Definition at line 51 of file User.h.
Constructor & Destructor Documentation
User::User ()
Konstruktor.
Definition at line 39 of file User.cpp.
References logonSuccess.
User::~User () [virtual]
Destruktor.
Definition at line 46 of file User.cpp.
Member Function Documentation
int User::getUsertype ()
Gibt den Usertype zurück.
Returns:
Typ des Benutzers (int)
Definition at line 133 of file User.cpp.
References usertype.
Referenced by NeuerUserDialog::NeuerUserDialog(), BEO_Timing::setUserRights(), and TableEditDialog::TableEditDialog().
void User::Init (QString username, QString password) throw (QString)
Initialisierung des Benutzers. Diese Methode wirft eine Exception, im Falle eines falschen Benutzernames oder Passworts.
Parameters:
username Benutzername des Benutzers
password Passwort des Benutzers
Definition at line 56 of file User.cpp.
References email, logonSuccess, name, password, rennen, username, and usertype.
Referenced by LogonDialog::on_LogonButton_released(), and RechteAnpassen::on_okButton_released().
void User::Init (QString username)
Initialisieren über den Benutzernamen.
Definition at line 90 of file User.cpp.
References email, name, password, rennen, and usertype.
bool User::checkPassword (QString password)
bool User::getRaceAuthority (int race)
Prüfen, ob der Benutzer die Berechtigung für ein Rennen hat.
Parameters:
race zu überprüfendes Rennen
Definition at line 118 of file User.cpp.
References rennen.
Referenced by HardwareKonfiguration::HardwareKonfiguration(), NeuerUserDialog::NeuerUserDialog(), RechteAnpassen::RechteAnpassen(), and BEO_Timing::Tree_Build().
bool User::getLogonSuccess ()
LogonSuccess überprüfen.
Definition at line 111 of file User.cpp.
References logonSuccess.
Referenced by BEO_Timing::BEO_Timing().
Friends And Related Function Documentation
friend class PasswordChangeDialog [friend]
Definition at line 60 of file User.h.
friend class NeuerUserDialog [friend]
Definition at line 61 of file User.h.
friend class RechteAnpassen [friend]
Definition at line 62 of file User.h.
Member Data Documentation
QString User::username [protected]
Definition at line 53 of file User.h.
Referenced by Init(), and PasswordChangeDialog::on_okButton_released().
QString User::name [protected]
Definition at line 54 of file User.h.
Referenced by Init().
QString User::email [protected]
Definition at line 55 of file User.h.
Referenced by Init().
QString User::password [protected]
Definition at line 56 of file User.h.
Referenced by Init(), RechteAnpassen::on_okButton_released(), PasswordChangeDialog::on_okButton_released(), and NeuerUserDialog::on_okButton_released().
int User::usertype [protected]
Definition at line 57 of file User.h.
Referenced by getUsertype(), Init(), and NeuerUserDialog::NeuerUserDialog().
QString User::rennen [protected]
Definition at line 58 of file User.h.
Referenced by getRaceAuthority(), Init(), and RechteAnpassen::on_okButton_released().
bool User::logonSuccess [protected]
Definition at line 59 of file User.h.
Referenced by getLogonSuccess(), Init(), and User().
The documentation for this class was generated from the following files:
User.h
User.cpp