BEO-Timing: RFIDInputDialog Class Reference
RFIDInputDialog Class Reference
Stellt die Eingabemaske, sowie die benötigten Funktionen zum auswerten von RFID-Tags eines beliebigen Lesers zur Verfügung.
#include <rfidinputdialog.h>
Public Member Functions
RFIDInputDialog (RFID_CR500 *pRfid, QWidget *parent=0)
Konstruktor.
~RFIDInputDialog ()
Destruktor.
Private Types
enum strecken {
StreckenKey, Streckenname, Startdatum, Enddatum,
Jahr, StreckentypKey
}
enum teilnehmer {
TeilnehmerKey, Name, Vorname, Adresse,
PLZ, Ort, Jahrgang, Geschlecht,
Nationalitaet, Team_Club, Email, Telefon,
Mobile, RFID_SNR
}
Private Slots
void on_okButton_released ()
Slot für Ok-Button.
void on_canButton_released ()
Slot für Abbrechen-Button.
void checkSingularity ()
überprüfen, ob der bisherige Eintrag einzigartig ist.
void on_nameLineEdit_textEdited ()
Slot für Textänderungen.
void on_vornameLineEdit_textEdited ()
Slot für Textänderungen.
void on_adresseLineEdit_textEdited ()
Slot für Textänderungen.
void on_plzLineEdit_textEdited ()
Slot für Textänderungen.
void on_ortLineEdit_textEdited ()
Slot für Textänderungen.
void on_telephonLineEdit_textEdited ()
Slot für Textänderungen.
void on_mobileLineEdit_textEdited ()
Slot für Textänderungen.
void on_emailLineEdit_textEdited ()
Slot für Textänderungen.
void on_clubLineEdit_textEdited ()
Slot für Textänderungen.
void on_nationalitaetComboBox_currentIndexChanged ()
Slot für Textänderungen.
void on_jahrgangSpinBox_valueChanged ()
Slot für Jahrgangsänderungen (aktualisieren der Kategorie).
void on_autoCheckBox_stateChanged ()
Slot für CheckBox "automatisches Vervollständigen".
Private Member Functions
QString toDateString (struct MYTIME *time, QString format="hh:mm:ss")
Zeiten aus der Struktur zur anzeige vorbereiten.
QString toDateString (struct MYDATE *date, QString format="dd. MMMM yyyy hh:mm:ss")
Zeiten aus der Struktur zur anzeige vorbereiten.
QStringList getStreckenNameTyp (int StreckenKey)
Informationen zum Streckentyp aus der Datenbank abrufen.
bool insertRacetime (int TeilnehmerKeyInt)
Einfügen der Fahrzeit in die Datenbank.
bool insertPersonAndTime ()
Eintragen des neuen Teilnehmers und der Zeit.
bool updatePerson (int TeilnehmerKeyInt)
Änderungen der Benutzerdaten in die Datenbank übertragen.
void fillForm (QSqlQuery *query)
Ausfüllen des gewählten Vorschlags in die Textfelder.
QString calculateKategorie (int jahrgang)
Berechne die Kategorie aufgrund der Altersbereiche in der Datenbank.
bool validation ()
Validierung der Einträge.
bool clearValidFlag ()
Löschen der Statusbits der Karte nach dem Auswerten.
Private Attributes
Ui::RFIDInputDialogClass ui
QSqlTableModel * teilnehmer
QString text
int TeilnehmerKeyInt
int index
RFID_CR500 * pRfid
bool autoInsert
Detailed Description
Stellt die Eingabemaske, sowie die benötigten Funktionen zum auswerten von RFID-Tags eines beliebigen Lesers zur Verfügung.
Definition at line 48 of file rfidinputdialog.h.
Member Enumeration Documentation
enum RFIDInputDialog::strecken [private]
Enumerator:
StreckenKey
Streckenname
Startdatum
Enddatum
Jahr
StreckentypKey
Definition at line 69 of file rfidinputdialog.h.
enum RFIDInputDialog::teilnehmer [private]
Enumerator:
TeilnehmerKey
Name
Vorname
Adresse
PLZ
Ort
Jahrgang
Geschlecht
Nationalitaet
Team_Club
Email
Telefon
Mobile
RFID_SNR
Definition at line 71 of file rfidinputdialog.h.
Constructor & Destructor Documentation
RFIDInputDialog::RFIDInputDialog (RFID_CR500 * pRfid, QWidget * parent = 0)
Konstruktor.
Parameters:
pRfid Pointer zur RFID-Leser Klasse
parent Pointer auf das aufrufende Objekt
Definition at line 41 of file rfidinputdialog.cpp.
References Ui_RFIDInputDialogClass::adresseLineEdit, autoInsert, calculateKategorie(), checkSingularity(), Ui_RFIDInputDialogClass::clubLineEdit, Ui_RFIDInputDialogClass::emailLineEdit, RFID_CR500::enddate, Ui_RFIDInputDialogClass::EndtimeLabel, Ui_RFIDInputDialogClass::FahrzeitLabel, getStreckenNameTyp(), Ui_RFIDInputDialogClass::jahrgangSpinBox, Ui_RFIDInputDialogClass::KategoriecomboBox, Ui_RFIDInputDialogClass::maenlichRadioButton, Ui_RFIDInputDialogClass::mobileLineEdit, Ui_RFIDInputDialogClass::nameLineEdit, Ui_RFIDInputDialogClass::nationalitaetComboBox, Ui_RFIDInputDialogClass::ortLineEdit, Ui_RFIDInputDialogClass::plzLineEdit, RFID_CR500::racetime, Ui_RFIDInputDialogClass::rfidsnrLabel, RFID_CR500::serial, Ui_RFIDInputDialogClass::setupUi(), Ui_RFIDInputDialogClass::StarttimeLabel, RFID_CR500::strecke, Ui_RFIDInputDialogClass::StreckennameLabel, Ui_RFIDInputDialogClass::StreckenTypLabel, TeilnehmerKeyInt, Ui_RFIDInputDialogClass::telephonLineEdit, toDateString(), ui, Ui_RFIDInputDialogClass::vornameLineEdit, and Ui_RFIDInputDialogClass::weiblichRadioButton.
RFIDInputDialog::~RFIDInputDialog ()
Destruktor.
Definition at line 133 of file rfidinputdialog.cpp.
Member Function Documentation
QString RFIDInputDialog::toDateString (struct MYTIME * time, QString format = "hh:mm:ss") [private]
Zeiten aus der Struktur zur anzeige vorbereiten.
Definition at line 140 of file rfidinputdialog.cpp.
References MYTIME::hour, MYTIME::minute, and MYTIME::second.
Referenced by insertRacetime(), and RFIDInputDialog().
QString RFIDInputDialog::toDateString (struct MYDATE * date, QString format = "dd. MMMM yyyy hh:mm:ss") [private]
Zeiten aus der Struktur zur anzeige vorbereiten.
Definition at line 150 of file rfidinputdialog.cpp.
References MYDATE::day, MYDATE::hour, MYDATE::minute, MYDATE::month, MYDATE::second, and MYDATE::year.
QStringList RFIDInputDialog::getStreckenNameTyp (int StreckenKey) [private]
Informationen zum Streckentyp aus der Datenbank abrufen.
Parameters:
StreckenKey Nummer der Strecke
Returns:
Liste mit den Informationen
Definition at line 165 of file rfidinputdialog.cpp.
References Streckenname, and StreckentypKey.
Referenced by RFIDInputDialog().
bool RFIDInputDialog::insertRacetime (int TeilnehmerKeyInt) [private]
Einfügen der Fahrzeit in die Datenbank.
Parameters:
TeilnehmerKeyInt Nummer des Teilnehmers
Definition at line 344 of file rfidinputdialog.cpp.
References RFID_CR500::enddate, Ui_RFIDInputDialogClass::KategoriecomboBox, pRfid, RFID_CR500::racetime, RFID_CR500::strecke, toDateString(), and ui.
Referenced by checkSingularity(), insertPersonAndTime(), and on_okButton_released().
bool RFIDInputDialog::insertPersonAndTime () [private]
Eintragen des neuen Teilnehmers und der Zeit.
Definition at line 392 of file rfidinputdialog.cpp.
References Ui_RFIDInputDialogClass::adresseLineEdit, Ui_RFIDInputDialogClass::clubLineEdit, Ui_RFIDInputDialogClass::emailLineEdit, insertRacetime(), Ui_RFIDInputDialogClass::jahrgangSpinBox, Ui_RFIDInputDialogClass::maenlichRadioButton, Ui_RFIDInputDialogClass::mobileLineEdit, Ui_RFIDInputDialogClass::nameLineEdit, Ui_RFIDInputDialogClass::nationalitaetComboBox, Ui_RFIDInputDialogClass::ortLineEdit, Ui_RFIDInputDialogClass::plzLineEdit, Ui_RFIDInputDialogClass::telephonLineEdit, ui, and Ui_RFIDInputDialogClass::vornameLineEdit.
Referenced by on_okButton_released().
bool RFIDInputDialog::updatePerson (int TeilnehmerKeyInt) [private]
Änderungen der Benutzerdaten in die Datenbank übertragen.
Definition at line 449 of file rfidinputdialog.cpp.
References Ui_RFIDInputDialogClass::adresseLineEdit, Ui_RFIDInputDialogClass::clubLineEdit, Ui_RFIDInputDialogClass::emailLineEdit, Ui_RFIDInputDialogClass::jahrgangSpinBox, Ui_RFIDInputDialogClass::maenlichRadioButton, Ui_RFIDInputDialogClass::mobileLineEdit, Ui_RFIDInputDialogClass::nameLineEdit, Ui_RFIDInputDialogClass::nationalitaetComboBox, Ui_RFIDInputDialogClass::ortLineEdit, Ui_RFIDInputDialogClass::plzLineEdit, Ui_RFIDInputDialogClass::telephonLineEdit, ui, and Ui_RFIDInputDialogClass::vornameLineEdit.
Referenced by on_okButton_released().
void RFIDInputDialog::fillForm (QSqlQuery * query) [private]
Ausfüllen des gewählten Vorschlags in die Textfelder.
Definition at line 319 of file rfidinputdialog.cpp.
References Adresse, Ui_RFIDInputDialogClass::adresseLineEdit, Ui_RFIDInputDialogClass::clubLineEdit, Email, Ui_RFIDInputDialogClass::emailLineEdit, Geschlecht, Jahrgang, Ui_RFIDInputDialogClass::jahrgangSpinBox, Ui_RFIDInputDialogClass::maenlichRadioButton, Mobile, Ui_RFIDInputDialogClass::mobileLineEdit, Name, Ui_RFIDInputDialogClass::nameLineEdit, Nationalitaet, Ui_RFIDInputDialogClass::nationalitaetComboBox, Ort, Ui_RFIDInputDialogClass::ortLineEdit, PLZ, Ui_RFIDInputDialogClass::plzLineEdit, Team_Club, Telefon, Ui_RFIDInputDialogClass::telephonLineEdit, ui, Vorname, Ui_RFIDInputDialogClass::vornameLineEdit, and Ui_RFIDInputDialogClass::weiblichRadioButton.
Referenced by checkSingularity().
QString RFIDInputDialog::calculateKategorie (int jahrgang) [private]
Berechne die Kategorie aufgrund der Altersbereiche in der Datenbank.
Definition at line 606 of file rfidinputdialog.cpp.
Referenced by checkSingularity(), on_jahrgangSpinBox_valueChanged(), and RFIDInputDialog().
bool RFIDInputDialog::validation () [private]
Validierung der Einträge.
Definition at line 656 of file rfidinputdialog.cpp.
References Ui_RFIDInputDialogClass::adresseLineEdit, Ui_RFIDInputDialogClass::maenlichRadioButton, Ui_RFIDInputDialogClass::nameLineEdit, Ui_RFIDInputDialogClass::ortLineEdit, Ui_RFIDInputDialogClass::plzLineEdit, ui, Ui_RFIDInputDialogClass::vornameLineEdit, and Ui_RFIDInputDialogClass::weiblichRadioButton.
Referenced by on_okButton_released().
bool RFIDInputDialog::clearValidFlag () [private]
Löschen der Statusbits der Karte nach dem Auswerten.
Definition at line 693 of file rfidinputdialog.cpp.
References RFID_CR500::clearValidFlag(), and pRfid.
Referenced by checkSingularity(), and on_okButton_released().
void RFIDInputDialog::on_okButton_released () [private, slot]
Slot für Ok-Button.
Definition at line 631 of file rfidinputdialog.cpp.
References clearValidFlag(), insertPersonAndTime(), insertRacetime(), TeilnehmerKeyInt, updatePerson(), and validation().
void RFIDInputDialog::on_canButton_released () [private, slot]
Slot für Abbrechen-Button.
Definition at line 705 of file rfidinputdialog.cpp.
References RFID_CR500::greenLED(), and pRfid.
void RFIDInputDialog::checkSingularity () [private, slot]
überprüfen, ob der bisherige Eintrag einzigartig ist.
Definition at line 186 of file rfidinputdialog.cpp.
References Adresse, Ui_RFIDInputDialogClass::adresseLineEdit, Ui_RFIDInputDialogClass::autoCheckBox, autoInsert, calculateKategorie(), clearValidFlag(), Ui_RFIDInputDialogClass::clubLineEdit, Email, Ui_RFIDInputDialogClass::emailLineEdit, fillForm(), Geschlecht, insertRacetime(), Jahrgang, Ui_RFIDInputDialogClass::KategoriecomboBox, Mobile, Ui_RFIDInputDialogClass::mobileLineEdit, Name, Ui_RFIDInputDialogClass::nameLineEdit, Nationalitaet, Ort, Ui_RFIDInputDialogClass::ortLineEdit, PLZ, Ui_RFIDInputDialogClass::plzLineEdit, Team_Club, TeilnehmerKey, TeilnehmerKeyInt, Telefon, Ui_RFIDInputDialogClass::telephonLineEdit, ui, Vorname, and Ui_RFIDInputDialogClass::vornameLineEdit.
Referenced by on_adresseLineEdit_textEdited(), on_autoCheckBox_stateChanged(), on_clubLineEdit_textEdited(), on_emailLineEdit_textEdited(), on_mobileLineEdit_textEdited(), on_nameLineEdit_textEdited(), on_ortLineEdit_textEdited(), on_plzLineEdit_textEdited(), on_telephonLineEdit_textEdited(), on_vornameLineEdit_textEdited(), and RFIDInputDialog().
void RFIDInputDialog::on_nameLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 525 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_vornameLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 532 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_adresseLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 539 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_plzLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 546 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_ortLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 553 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_telephonLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 560 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_mobileLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 567 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_emailLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 574 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_clubLineEdit_textEdited () [private, slot]
Slot für Textänderungen.
Definition at line 581 of file rfidinputdialog.cpp.
References checkSingularity().
void RFIDInputDialog::on_nationalitaetComboBox_currentIndexChanged () [private, slot]
Slot für Textänderungen.
Definition at line 588 of file rfidinputdialog.cpp.
void RFIDInputDialog::on_jahrgangSpinBox_valueChanged () [private, slot]
Slot für Jahrgangsänderungen (aktualisieren der Kategorie).
Definition at line 595 of file rfidinputdialog.cpp.
References calculateKategorie(), Ui_RFIDInputDialogClass::jahrgangSpinBox, Ui_RFIDInputDialogClass::KategoriecomboBox, and ui.
void RFIDInputDialog::on_autoCheckBox_stateChanged () [private, slot]
Slot für CheckBox "automatisches Vervollständigen".
Definition at line 622 of file rfidinputdialog.cpp.
References Ui_RFIDInputDialogClass::autoCheckBox, autoInsert, checkSingularity(), and ui.
Member Data Documentation
Ui::RFIDInputDialogClass RFIDInputDialog::ui [private]
Definition at line 57 of file rfidinputdialog.h.
Referenced by checkSingularity(), fillForm(), insertPersonAndTime(), insertRacetime(), on_autoCheckBox_stateChanged(), on_jahrgangSpinBox_valueChanged(), RFIDInputDialog(), updatePerson(), and validation().
QSqlTableModel* RFIDInputDialog::teilnehmer [private]
Definition at line 68 of file rfidinputdialog.h.
QString RFIDInputDialog::text [private]
Definition at line 73 of file rfidinputdialog.h.
int RFIDInputDialog::TeilnehmerKeyInt [private]
Definition at line 74 of file rfidinputdialog.h.
Referenced by checkSingularity(), on_okButton_released(), and RFIDInputDialog().
int RFIDInputDialog::index [private]
Definition at line 75 of file rfidinputdialog.h.
RFID_CR500* RFIDInputDialog::pRfid [private]
Definition at line 76 of file rfidinputdialog.h.
Referenced by clearValidFlag(), insertRacetime(), and on_canButton_released().
bool RFIDInputDialog::autoInsert [private]
Definition at line 77 of file rfidinputdialog.h.
Referenced by checkSingularity(), on_autoCheckBox_stateChanged(), and RFIDInputDialog().
The documentation for this class was generated from the following files:
RFID_Reader/rfidinputdialog.h
RFID_Reader/rfidinputdialog.cpp