BEO-Timing: HardwareKonfiguration Class Reference
HardwareKonfiguration Class Reference
Dieser Dialog erstellt eine Konfiguration fuer eine Anlage.
#include <hardwarekonfiguration.h>
Public Member Functions
HardwareKonfiguration (User *user, QWidget *parent=0)
Konstruktor.
~HardwareKonfiguration ()
Destruktor.
Private Types
enum stationen {
StationenKey, typ, sim_pin, sim_puk,
sms_center, server_ip, server_port, gprs_username,
gprs_pwd, ftp_server, ftp_username, ftp_pwd
}
enum streckentypen {
Rennvelo = 1, Mountainbike = 2, Laufen = 3, Walking = 4,
Langlauf = 5, Inline = 6
}
Private Slots
void on_okButton_released ()
Slot für OK-Button.
void on_canButton_released ()
Slot für Abbrechen-Button.
void on_streckenTreeWidget_currentItemChanged (QTreeWidgetItem *current, QTreeWidgetItem *previous)
Slot für Änderungen in der Baumauswahl.
Private Member Functions
QStringList getSelectedRennen ()
ausgewählte Rennen im Baum bestimmen
bool validation ()
Validierung für den Dialog.
QStringList getSommertime ()
aktuelle Sommerzeit aus der Datenbank lesen
Private Attributes
bool use_gprs
QString funktion
Ui::HardwareKonfigurationClass ui
Detailed Description
Dieser Dialog erstellt eine Konfiguration fuer eine Anlage.
Definition at line 41 of file hardwarekonfiguration.h.
Member Enumeration Documentation
enum HardwareKonfiguration::stationen [private]
Enumerator:
StationenKey
typ
sim_pin
sim_puk
sms_center
server_ip
server_port
gprs_username
gprs_pwd
ftp_server
ftp_username
ftp_pwd
Definition at line 50 of file hardwarekonfiguration.h.
enum HardwareKonfiguration::streckentypen [private]
Enumerator:
Rennvelo
Mountainbike
Laufen
Walking
Langlauf
Inline
Definition at line 53 of file hardwarekonfiguration.h.
Constructor & Destructor Documentation
HardwareKonfiguration::HardwareKonfiguration (User * user, QWidget * parent = 0)
Konstruktor.
Definition at line 38 of file hardwarekonfiguration.cpp.
References Ui_HardwareKonfigurationClass::ftpserverLabel, Ui_HardwareKonfigurationClass::ftpuserLabel, funktion, User::getRaceAuthority(), Inline, Langlauf, Laufen, Mountainbike, Rennvelo, Ui_HardwareKonfigurationClass::setupUi(), Ui_HardwareKonfigurationClass::smsLineEdit, Ui_HardwareKonfigurationClass::stationComboBox, Ui_HardwareKonfigurationClass::streckenTreeWidget, ui, use_gprs, and Walking.
HardwareKonfiguration::~HardwareKonfiguration ()
Destruktor.
Definition at line 147 of file hardwarekonfiguration.cpp.
Member Function Documentation
QStringList HardwareKonfiguration::getSelectedRennen () [private]
ausgewählte Rennen im Baum bestimmen
Definition at line 191 of file hardwarekonfiguration.cpp.
References Ui_HardwareKonfigurationClass::streckenTreeWidget, and ui.
Referenced by on_okButton_released(), and validation().
bool HardwareKonfiguration::validation () [private]
Validierung für den Dialog.
Definition at line 318 of file hardwarekonfiguration.cpp.
References getSelectedRennen(), Ui_HardwareKonfigurationClass::smsLineEdit, and ui.
Referenced by on_okButton_released().
QStringList HardwareKonfiguration::getSommertime () [private]
aktuelle Sommerzeit aus der Datenbank lesen
Definition at line 154 of file hardwarekonfiguration.cpp.
References Ui_HardwareKonfigurationClass::streckenTreeWidget, and ui.
Referenced by on_okButton_released().
void HardwareKonfiguration::on_okButton_released () [private, slot]
Slot für OK-Button.
Definition at line 211 of file hardwarekonfiguration.cpp.
References Ui_HardwareKonfigurationClass::ausSpinBox, Ui_HardwareKonfigurationClass::einSpinBox, funktion, getSelectedRennen(), getSommertime(), Ui_HardwareKonfigurationClass::gprsCheckBox, Ui_HardwareKonfigurationClass::smsLineEdit, Ui_HardwareKonfigurationClass::stationComboBox, ui, and validation().
void HardwareKonfiguration::on_canButton_released () [private, slot]
Slot für Abbrechen-Button.
Definition at line 300 of file hardwarekonfiguration.cpp.
void HardwareKonfiguration::on_streckenTreeWidget_currentItemChanged (QTreeWidgetItem * current, QTreeWidgetItem * previous) [private, slot]
Slot für Änderungen in der Baumauswahl.
Definition at line 307 of file hardwarekonfiguration.cpp.
References Ui_HardwareKonfigurationClass::streckenTreeWidget, and ui.
Member Data Documentation
bool HardwareKonfiguration::use_gprs [private]
Definition at line 56 of file hardwarekonfiguration.h.
Referenced by HardwareKonfiguration().
QString HardwareKonfiguration::funktion [private]
Definition at line 57 of file hardwarekonfiguration.h.
Referenced by HardwareKonfiguration(), and on_okButton_released().
Ui::HardwareKonfigurationClass HardwareKonfiguration::ui [private]
Definition at line 59 of file hardwarekonfiguration.h.
Referenced by getSelectedRennen(), getSommertime(), HardwareKonfiguration(), on_okButton_released(), on_streckenTreeWidget_currentItemChanged(), and validation().
The documentation for this class was generated from the following files:
hardwarekonfiguration.h
hardwarekonfiguration.cpp