BEO-Timing: DB_Thread Class Reference
DB_Thread Class Reference
Dieser Thread ueberprueft alle 5 Sekunden die Verbindung zur Datenbank.
#include <dbThread.h>
Public Types
enum __state { running, stopp, pause, restart }
typedef enum DB_Thread::__state STATE
Signals
void checkDB ()
Public Member Functions
DB_Thread ()
Konstruktor.
~DB_Thread ()
Destruktor.
void stop ()
Stoppen des Threads.
void setState (STATE state)
setzen des States der Zustandsmaschine
int getState ()
lesen des States der Zustandsmaschine
Protected Member Functions
void run ()
Überschreiben der vererbten Funktion "run".
Private Attributes
volatile bool stopped
volatile STATE state
Database * pMySQL
Detailed Description
Dieser Thread ueberprueft alle 5 Sekunden die Verbindung zur Datenbank.
Definition at line 42 of file dbThread.h.
Member Typedef Documentation
typedef enum DB_Thread::__state DB_Thread::STATE
Member Enumeration Documentation
enum DB_Thread::__state
Enumerator:
running
stopp
pause
restart
Definition at line 50 of file dbThread.h.
Constructor & Destructor Documentation
DB_Thread::DB_Thread ()
Konstruktor.
Definition at line 37 of file dbThread.cpp.
References running, state, and stopped.
DB_Thread::~DB_Thread ()
Destruktor.
Definition at line 46 of file dbThread.cpp.
Member Function Documentation
void DB_Thread::stop ()
Stoppen des Threads.
Definition at line 52 of file dbThread.cpp.
References stopped.
Referenced by BEO_Timing::~BEO_Timing().
void DB_Thread::setState (STATE state)
setzen des States der Zustandsmaschine
Definition at line 58 of file dbThread.cpp.
Referenced by BEO_Timing::mysqlConnection().
int DB_Thread::getState ()
lesen des States der Zustandsmaschine
Definition at line 64 of file dbThread.cpp.
References state.
Referenced by BEO_Timing::checkDB().
void DB_Thread::run () [protected]
Überschreiben der vererbten Funktion "run".
Definition at line 71 of file dbThread.cpp.
References checkDB(), DB_REFRESH_RATE_ms, pause, restart, running, state, stopp, and stopped.
void DB_Thread::checkDB () [signal]
Definition at line 73 of file moc_dbThread.cpp.
Referenced by run().
Member Data Documentation
volatile bool DB_Thread::stopped [private]
Definition at line 58 of file dbThread.h.
Referenced by DB_Thread(), run(), and stop().
volatile STATE DB_Thread::state [private]
Definition at line 59 of file dbThread.h.
Referenced by DB_Thread(), getState(), and run().
Database* DB_Thread::pMySQL [private]
Definition at line 60 of file dbThread.h.
The documentation for this class was generated from the following files:
dbThread.h
dbThread.cpp
debug/moc_dbThread.cpp