BEO-Timing: RFID_CR500 Class Reference
RFID_CR500 Class Reference
Enthält alle Eigenschaften des RFID-Lesers CR500-USB.
#include <RFID_CR500.h>
Public Member Functions
RFID_CR500 ()
Konstruktor.
virtual ~RFID_CR500 ()
Destruktor.
bool findCard ()
Karte im Feld suchen.
bool readData ()
Lesen der gefundenen Karte.
bool clearValidFlag ()
Löschen der Flags, um die Karte als ausgewertet kennzuzeichnen.
void greenLED ()
Stellt die LED des Lesers auf Grün.
bool isConnected ()
Funktion zum Testen der Verbindung zum Leser.
Private Member Functions
void myStrcat (TCHAR *op, int size)
Strcat für UTF-8.
void myCout (TCHAR *op, int size)
Ausgabe für UTF-8 String.
void init_RFID ()
Initialisieren des RFID-Lesers.
Private Attributes
bool connected
unsigned short icdev
QString serial
QString oldSerial
qint16 strecke
struct MYDATE startdate enddate
struct MYTIME racetime
Friends
class RFIDInputDialog
Detailed Description
Enthält alle Eigenschaften des RFID-Lesers CR500-USB.
Definition at line 90 of file RFID_CR500.h.
Constructor & Destructor Documentation
RFID_CR500::RFID_CR500 ()
Konstruktor.
Definition at line 42 of file RFID_CR500.cpp.
References connected, GREEN_LED, icdev, init_RFID(), LIB_SUCCESS, BEO_Timing::updateMessage(), and BEO_Timing::updateRFID().
RFID_CR500::~RFID_CR500 () [virtual]
Destruktor.
Definition at line 91 of file RFID_CR500.cpp.
Member Function Documentation
bool RFID_CR500::findCard ()
Karte im Feld suchen.
Definition at line 259 of file RFID_CR500.cpp.
References bcnt, connected, GREEN_LED, icdev, mode, NO_LED, oldSerial, serial, Snr, TagType, BEO_Timing::updateMessage(), and YELLOW_LED.
Referenced by BEO_Timing::checkRFID(), and clearValidFlag().
bool RFID_CR500::readData ()
Lesen der gefundenen Karte.
Definition at line 300 of file RFID_CR500.cpp.
References connected, enddate, icdev, oldSerial, pData, racetime, RFID_ADR_ENDTIME, RFID_ADR_STATUS, serial, strecke, TAG_STATUS_ENDVALID, TAG_STATUS_MANUALCLEARED, TAG_STATUS_REGISTERED, TAG_STATUS_STARTVALID, and TAG_STATUS_STRECKENVALID.
Referenced by BEO_Timing::checkRFID().
bool RFID_CR500::clearValidFlag ()
Löschen der Flags, um die Karte als ausgewertet kennzuzeichnen.
Definition at line 392 of file RFID_CR500.cpp.
References connected, findCard(), GREEN_LED, icdev, oldSerial, pData, RFID_ADR_STATUS, serial, TAG_STATUS_ENDVALID, TAG_STATUS_STARTVALID, and TAG_STATUS_STRECKENVALID.
Referenced by RFIDInputDialog::clearValidFlag().
void RFID_CR500::greenLED ()
Stellt die LED des Lesers auf Grün.
Definition at line 424 of file RFID_CR500.cpp.
References GREEN_LED, and icdev.
Referenced by RFIDInputDialog::on_canButton_released().
bool RFID_CR500::isConnected ()
Funktion zum Testen der Verbindung zum Leser.
Definition at line 431 of file RFID_CR500.cpp.
References connected, and icdev.
Referenced by BEO_Timing::checkRFID(), and BEO_Timing::CR500_verbinden().
void RFID_CR500::myStrcat (TCHAR * op, int size) [private]
Strcat für UTF-8.
Definition at line 98 of file RFID_CR500.cpp.
Referenced by init_RFID().
void RFID_CR500::myCout (TCHAR * op, int size) [private]
Ausgabe für UTF-8 String.
Definition at line 122 of file RFID_CR500.cpp.
Referenced by init_RFID().
void RFID_CR500::init_RFID () [private]
Initialisieren des RFID-Lesers.
Definition at line 135 of file RFID_CR500.cpp.
References myCout(), and myStrcat().
Referenced by RFID_CR500().
Friends And Related Function Documentation
friend class RFIDInputDialog [friend]
Definition at line 112 of file RFID_CR500.h.
Member Data Documentation
bool RFID_CR500::connected [private]
Definition at line 105 of file RFID_CR500.h.
Referenced by clearValidFlag(), findCard(), isConnected(), readData(), and RFID_CR500().
unsigned short RFID_CR500::icdev [private]
Definition at line 106 of file RFID_CR500.h.
Referenced by clearValidFlag(), findCard(), greenLED(), isConnected(), readData(), and RFID_CR500().
QString RFID_CR500::serial [private]
Definition at line 107 of file RFID_CR500.h.
Referenced by clearValidFlag(), findCard(), readData(), and RFIDInputDialog::RFIDInputDialog().
QString RFID_CR500::oldSerial [private]
Definition at line 108 of file RFID_CR500.h.
Referenced by clearValidFlag(), findCard(), and readData().
qint16 RFID_CR500::strecke [private]
Definition at line 109 of file RFID_CR500.h.
Referenced by RFIDInputDialog::insertRacetime(), readData(), and RFIDInputDialog::RFIDInputDialog().
struct MYDATE startdate RFID_CR500::enddate [read, private]
Definition at line 110 of file RFID_CR500.h.
Referenced by RFIDInputDialog::insertRacetime(), readData(), and RFIDInputDialog::RFIDInputDialog().
struct MYTIME RFID_CR500::racetime [read, private]
Definition at line 111 of file RFID_CR500.h.
Referenced by RFIDInputDialog::insertRacetime(), readData(), and RFIDInputDialog::RFIDInputDialog().
The documentation for this class was generated from the following files:
RFID_Reader/RFID_CR500.h
RFID_Reader/RFID_CR500.cpp