BEO-Timing: LogonDialog Class Reference
LogonDialog Class Reference
Dieser Dialog ist das Login des Programms. Es dient zur Authentifizierung des Benutzers.
#include <logondialog.h>
Public Member Functions
LogonDialog (User *user, QApplication *a, BEO_Timing *w, QWidget *parent=0)
Konstruktor.
~LogonDialog ()
Destruktor.
Protected Attributes
QApplication * a
BEO_Timing * w
User * user
Ui::LogonDialogClass ui
Private Slots
void on_LogonButton_released ()
Slot für Logon-Button.
void on_BeendenButton_released ()
Slot für Beenden-Button.
Detailed Description
Dieser Dialog ist das Login des Programms. Es dient zur Authentifizierung des Benutzers.
Definition at line 43 of file logondialog.h.
Constructor & Destructor Documentation
LogonDialog::LogonDialog (User * user, QApplication * a, BEO_Timing * w, QWidget * parent = 0)
Konstruktor.
Parameters:
user Pointer auf den angemeldeten Benutzer
a Pointer auf die Hauptapplikation
w Pointer auf das Hauptfenster
parent Pointer auf parent
Definition at line 46 of file logondialog.cpp.
References Ui_LogonDialogClass::setupUi(), and ui.
LogonDialog::~LogonDialog ()
Destruktor.
Definition at line 61 of file logondialog.cpp.
Member Function Documentation
void LogonDialog::on_LogonButton_released () [private, slot]
Slot für Logon-Button.
Definition at line 75 of file logondialog.cpp.
References Ui_LogonDialogClass::BenutzernameEdit, User::Init(), md5_buffer(), md5_init(), Ui_LogonDialogClass::PasswortLabel_2, ui, BEO_Timing::updateUserStatus(), user, and w.
void LogonDialog::on_BeendenButton_released () [private, slot]
Slot für Beenden-Button.
Definition at line 69 of file logondialog.cpp.
Member Data Documentation
QApplication* LogonDialog::a [protected]
Definition at line 52 of file logondialog.h.
BEO_Timing* LogonDialog::w [protected]
Definition at line 53 of file logondialog.h.
Referenced by on_LogonButton_released().
User* LogonDialog::user [protected]
Definition at line 54 of file logondialog.h.
Referenced by on_LogonButton_released().
Ui::LogonDialogClass LogonDialog::ui [protected]
Definition at line 55 of file logondialog.h.
Referenced by LogonDialog(), and on_LogonButton_released().
The documentation for this class was generated from the following files:
logondialog.h
logondialog.cpp