BEO-Timing: BEO_Timing Class Reference
BEO_Timing Class Reference
Hauptklasse der Applikation.
#include <beo_timing.h>
Public Slots
void Tree_Build ()
Füllt die Baumansicht mit Ihalt, entsprechend der Benutzerrechte.
Public Member Functions
BEO_Timing (QSplashScreen *splash, QApplication *a, QWidget *parent=0)
Konstruktor.
~BEO_Timing ()
Destruktor.
void Read_Race (int StreckenKey)
Stellt die Rangliste dar.
void Tree_Settings ()
Bereitet die Baumansicht zur Darstellung vor.
void addRow (int columns)
QString getTimeCount (int StreckenKey)
Bestimmt die Anzahl Fahrzeiten für eine Strecke.
Static Public Member Functions
static void updateUserStatus (QString username)
static void updateRFID (QString rfid)
static void updateMessage (QString message)
Protected Attributes
RechteAnpassen * rechte
LogfileLesenDialog * logfile
HardwareKonfiguration * config
NeuerUserDialog * newUser
PasswordChangeDialog * pwd
NeuesRennenDialog * neu
Private Types
enum streckentypen {
Rennvelo = 1, Mountainbike = 2, Laufen = 3, Walking = 4,
Langlauf = 5, Inline = 6
}
enum teilnehmer {
Name, Vorname, Adresse, PLZ,
Ort, Nationalitaet, Jahrgang, Geschlecht,
Email, Telefon, Mobile, Team_Club,
Kategorie, Fahrzeit, Rueckstand, RFID_SNR,
StreckenKey, TimeID, TimeKey, TeilnehmerKey
}
Private Slots
void Tree_Changed ()
Reagiert auf eine Änderung der Auswahl im Baum.
void Table_Edit ()
Aufrufen des TableEdit-Dialogs mit den richtigen Parametern.
void checkRFID ()
Prüfen ob eine RFID-Karte im Feld ist.
void checkDB ()
Datenbankverbindung ueberpruefen.
void NeuesRennen ()
Aufrufen des NeuesRennen-Dialogs.
void exportToCsv ()
Exportieren der Rangliste im CSV-Format.
void changePwd ()
Passwort ändern Dialog öffnen.
void neuerUser ()
Neuer Benutzer - Dialog öffnen.
void buildConfiguration ()
Konfiguration erstellen - Dialog öffnen.
void readLogFile ()
Log-Datei Lesen - Dialog öffnen.
void rechteAnpassen ()
Benutzerreche anpassen - Dialog öffnen.
void about ()
About - Dialog der Managementsoftware anzeigen.
void rfidConnection (bool)
Verbindung zum RFID-Leser herstellen bzw. trennen.
void mysqlConnection (bool)
Verbindung zur Datenbank herstellen bzw. trennen (experimentell, nur Superadmin).
void purge ()
Datenbank bereinigen. Alle "(Noch nicht ausgewertet)"-Einträge entfernen.
void optimieren ()
Optimieren der Tabellen in der Datenbank.
void CR500_verbinden ()
Verbinden des RFID-Lesers.
Private Member Functions
void createStatusBar ()
Erstellt die Statusbar mit den drei Labeln.
void createMenu ()
Verbindet die Aktionen mit dem Slots (Benutzermenue).
void createToolbar ()
Erstellt die Symbolliste mit den ausgewählten Aktionen.
void setUserRights ()
Setzt die Benutzerrechte für die verschiedenen Aktionen.
void newVersion ()
Versionscheck.
Private Attributes
Ui::BEO_TimingClass ui
User * user
QApplication * a
RFID_Thread * thread
QTableView * view
QTreeWidget * raceTree
Database * pMySQL
DB_Thread * pMySQL_thread
QToolBar * toolbar
RFID_CR500 * pRfid
bool version
Static Private Attributes
static QLabel * userLabel
static QLabel * connectionLabel
static QLabel * messageLabel
Detailed Description
Hauptklasse der Applikation.
Definition at line 59 of file beo_timing.h.
Member Enumeration Documentation
enum BEO_Timing::streckentypen [private]
Enumerator:
Rennvelo
Mountainbike
Laufen
Walking
Langlauf
Inline
Definition at line 86 of file beo_timing.h.
enum BEO_Timing::teilnehmer [private]
Enumerator:
Name
Vorname
Adresse
PLZ
Ort
Nationalitaet
Jahrgang
Geschlecht
Email
Telefon
Mobile
Team_Club
Kategorie
Fahrzeit
Rueckstand
RFID_SNR
StreckenKey
TimeID
TimeKey
TeilnehmerKey
Definition at line 87 of file beo_timing.h.
Constructor & Destructor Documentation
BEO_Timing::BEO_Timing (QSplashScreen * splash, QApplication * a, QWidget * parent = 0)
Konstruktor.
Parameters:
splash Pointer auf den Splashscreen
a Pointer auf die Hauptapplikation
parent Pointer auf das aufrufende Element
Definition at line 56 of file beo_timing.cpp.
References checkDB(), checkRFID(), CR500_verbinden(), createMenu(), createStatusBar(), createToolbar(), Database::getDb(), User::getLogonSuccess(), newVersion(), pMySQL, pMySQL_thread, Ui_BEO_TimingClass::setupUi(), setUserRights(), thread, Tree_Build(), Tree_Settings(), ui, user, and version.
BEO_Timing::~BEO_Timing ()
Destruktor.
Definition at line 148 of file beo_timing.cpp.
References pMySQL_thread, pRfid, RFID_Thread::stop(), DB_Thread::stop(), and thread.
Member Function Documentation
void BEO_Timing::Read_Race (int StreckenNummer)
Stellt die Rangliste dar.
Parameters:
StreckenNummer Strecke, welche dargestellt werden soll.
Definition at line 344 of file beo_timing.cpp.
References Adresse, Email, Fahrzeit, Geschlecht, Jahrgang, Kategorie, Mobile, model, Name, Nationalitaet, Ort, PLZ, Ui_BEO_TimingClass::RanglistenTableView, Ui_BEO_TimingClass::RennenTreeWidget, RFID_SNR, Rueckstand, StreckenKey, Team_Club, TeilnehmerKey, Telefon, TimeID, TimeKey, ui, view, and Vorname.
Referenced by TableEditDialog::on_BestaetigenButton_released(), and Tree_Changed().
void BEO_Timing::Tree_Settings ()
Bereitet die Baumansicht zur Darstellung vor.
Definition at line 233 of file beo_timing.cpp.
References raceTree, Ui_BEO_TimingClass::RennenTreeWidget, Tree_Changed(), and ui.
Referenced by BEO_Timing().
static void BEO_Timing::updateUserStatus (QString username) [inline, static]
Definition at line 68 of file beo_timing.h.
References userLabel.
Referenced by LogonDialog::on_LogonButton_released().
static void BEO_Timing::updateRFID (QString rfid) [inline, static]
Definition at line 69 of file beo_timing.h.
References connectionLabel.
Referenced by RFID_CR500::RFID_CR500().
static void BEO_Timing::updateMessage (QString message) [inline, static]
Definition at line 70 of file beo_timing.h.
References messageLabel.
Referenced by RFID_CR500::findCard(), and RFID_CR500::RFID_CR500().
void BEO_Timing::addRow (int columns)
QString BEO_Timing::getTimeCount (int StreckenKey)
Bestimmt die Anzahl Fahrzeiten für eine Strecke.
Parameters:
StreckenKey Streckennummer
Definition at line 332 of file beo_timing.cpp.
Referenced by Tree_Build().
void BEO_Timing::createStatusBar () [private]
Erstellt die Statusbar mit den drei Labeln.
Definition at line 429 of file beo_timing.cpp.
References connectionLabel, messageLabel, and userLabel.
Referenced by BEO_Timing().
void BEO_Timing::createMenu () [private]
Verbindet die Aktionen mit dem Slots (Benutzermenue).
Definition at line 164 of file beo_timing.cpp.
References a, about(), Ui_BEO_TimingClass::actionAbout, Ui_BEO_TimingClass::actionAbout_Qt, Ui_BEO_TimingClass::actionAktualisieren, Ui_BEO_TimingClass::actionBeenden, Ui_BEO_TimingClass::actionBenutzerrechte_ndern, Ui_BEO_TimingClass::actionDatenbank, Ui_BEO_TimingClass::actionDatenbank_optimieren, Ui_BEO_TimingClass::actionEintrag_Editieren, Ui_BEO_TimingClass::actionExportieren_als_CSV, Ui_BEO_TimingClass::actionKonfiguration_erstellen, Ui_BEO_TimingClass::actionLog_Datei_auslesen, Ui_BEO_TimingClass::actionNeuer_Benutzer_erstellen_3, Ui_BEO_TimingClass::actionNeues_Rennen_erfassen, Ui_BEO_TimingClass::actionPasswort_ndern, Ui_BEO_TimingClass::actionRFID_Leser, Ui_BEO_TimingClass::actionRFID_Leser_verbinden, Ui_BEO_TimingClass::actionVerwaiste_Eintr_ge_entfernen, buildConfiguration(), changePwd(), CR500_verbinden(), exportToCsv(), mysqlConnection(), neuerUser(), NeuesRennen(), optimieren(), purge(), readLogFile(), rechteAnpassen(), rfidConnection(), Table_Edit(), Tree_Build(), and ui.
Referenced by BEO_Timing().
void BEO_Timing::createToolbar () [private]
Erstellt die Symbolliste mit den ausgewählten Aktionen.
Definition at line 219 of file beo_timing.cpp.
References Ui_BEO_TimingClass::actionAktualisieren, Ui_BEO_TimingClass::actionBeenden, Ui_BEO_TimingClass::actionEintrag_Editieren, Ui_BEO_TimingClass::actionExportieren_als_CSV, Ui_BEO_TimingClass::actionNeuer_Benutzer_erstellen_3, Ui_BEO_TimingClass::actionNeues_Rennen_erfassen, Ui_BEO_TimingClass::actionRFID_Leser, toolbar, and ui.
Referenced by BEO_Timing().
void BEO_Timing::setUserRights () [private]
Setzt die Benutzerrechte für die verschiedenen Aktionen.
Definition at line 187 of file beo_timing.cpp.
References Ui_BEO_TimingClass::actionBenutzerrechte_ndern, Ui_BEO_TimingClass::actionDatenbank, Ui_BEO_TimingClass::actionDatenbank_optimieren, Ui_BEO_TimingClass::actionEintrag_Editieren, Ui_BEO_TimingClass::actionKonfiguration_erstellen, Ui_BEO_TimingClass::actionLog_Datei_auslesen, Ui_BEO_TimingClass::actionNeuer_Benutzer_erstellen_3, Ui_BEO_TimingClass::actionNeues_Rennen_erfassen, Ui_BEO_TimingClass::actionRFID_Leser, Ui_BEO_TimingClass::actionRFID_Leser_verbinden, Ui_BEO_TimingClass::actionVerwaiste_Eintr_ge_entfernen, User::administrator, User::getUsertype(), User::manager, User::superadministrator, ui, User::user, and user.
Referenced by BEO_Timing().
void BEO_Timing::newVersion () [private]
Versionscheck.
Definition at line 712 of file beo_timing.cpp.
References VERSION, and version.
Referenced by BEO_Timing().
void BEO_Timing::Tree_Build () [slot]
Füllt die Baumansicht mit Ihalt, entsprechend der Benutzerrechte.
Definition at line 252 of file beo_timing.cpp.
References User::getRaceAuthority(), getTimeCount(), Inline, Langlauf, Laufen, Mountainbike, raceTree, Ui_BEO_TimingClass::RennenTreeWidget, Rennvelo, ui, user, and Walking.
Referenced by BEO_Timing(), createMenu(), and NeuesRennen().
void BEO_Timing::Tree_Changed () [private, slot]
Reagiert auf eine Änderung der Auswahl im Baum.
Definition at line 321 of file beo_timing.cpp.
References raceTree, and Read_Race().
Referenced by Tree_Settings().
void BEO_Timing::Table_Edit () [private, slot]
Aufrufen des TableEdit-Dialogs mit den richtigen Parametern.
Definition at line 451 of file beo_timing.cpp.
References model, TeilnehmerKey, user, and view.
Referenced by createMenu().
void BEO_Timing::checkRFID () [private, slot]
Prüfen ob eine RFID-Karte im Feld ist.
Definition at line 496 of file beo_timing.cpp.
References RFID_CR500::findCard(), RFID_CR500::isConnected(), pRfid, and RFID_CR500::readData().
Referenced by BEO_Timing().
void BEO_Timing::checkDB () [private, slot]
Datenbankverbindung ueberpruefen.
Definition at line 525 of file beo_timing.cpp.
References Database::getDb(), DB_Thread::getState(), pMySQL, pMySQL_thread, DB_Thread::restart, DB_Thread::running, and DB_Thread::stopp.
Referenced by BEO_Timing().
void BEO_Timing::NeuesRennen () [private, slot]
Aufrufen des NeuesRennen-Dialogs.
Definition at line 477 of file beo_timing.cpp.
References neu, and Tree_Build().
Referenced by createMenu().
void BEO_Timing::exportToCsv () [private, slot]
Exportieren der Rangliste im CSV-Format.
Definition at line 557 of file beo_timing.cpp.
References model, and view.
Referenced by createMenu().
void BEO_Timing::changePwd () [private, slot]
Passwort ändern Dialog öffnen.
Definition at line 596 of file beo_timing.cpp.
References pwd, and user.
Referenced by createMenu().
void BEO_Timing::neuerUser () [private, slot]
Neuer Benutzer - Dialog öffnen.
Definition at line 611 of file beo_timing.cpp.
References newUser, and user.
Referenced by createMenu().
void BEO_Timing::buildConfiguration () [private, slot]
Konfiguration erstellen - Dialog öffnen.
Definition at line 625 of file beo_timing.cpp.
References config, and user.
Referenced by createMenu().
void BEO_Timing::readLogFile () [private, slot]
Log-Datei Lesen - Dialog öffnen.
Definition at line 640 of file beo_timing.cpp.
References logfile.
Referenced by createMenu().
void BEO_Timing::rechteAnpassen () [private, slot]
Benutzerreche anpassen - Dialog öffnen.
Definition at line 654 of file beo_timing.cpp.
References rechte, and user.
Referenced by createMenu().
void BEO_Timing::about () [private, slot]
About - Dialog der Managementsoftware anzeigen.
Definition at line 668 of file beo_timing.cpp.
Referenced by createMenu().
void BEO_Timing::rfidConnection (bool checked) [private, slot]
Verbindung zum RFID-Leser herstellen bzw. trennen.
Definition at line 685 of file beo_timing.cpp.
References pRfid, RFID_Thread::restart, RFID_Thread::setRFID(), RFID_Thread::setState(), RFID_Thread::stopp, and thread.
Referenced by createMenu().
void BEO_Timing::mysqlConnection (bool checked) [private, slot]
Verbindung zur Datenbank herstellen bzw. trennen (experimentell, nur Superadmin).
Definition at line 700 of file beo_timing.cpp.
References pMySQL_thread, DB_Thread::restart, DB_Thread::setState(), and DB_Thread::stopp.
Referenced by createMenu().
void BEO_Timing::purge () [private, slot]
Datenbank bereinigen. Alle "(Noch nicht ausgewertet)"-Einträge entfernen.
Definition at line 725 of file beo_timing.cpp.
Referenced by createMenu().
void BEO_Timing::optimieren () [private, slot]
Optimieren der Tabellen in der Datenbank.
Definition at line 763 of file beo_timing.cpp.
Referenced by createMenu().
void BEO_Timing::CR500_verbinden () [private, slot]
Verbinden des RFID-Lesers.
Definition at line 782 of file beo_timing.cpp.
References Ui_BEO_TimingClass::actionRFID_Leser, Ui_BEO_TimingClass::actionRFID_Leser_verbinden, RFID_CR500::isConnected(), RFID_Thread::pause, pRfid, RFID_Thread::running, RFID_Thread::setRFID(), RFID_Thread::setState(), thread, and ui.
Referenced by BEO_Timing(), and createMenu().
Member Data Documentation
RechteAnpassen* BEO_Timing::rechte [protected]
Definition at line 77 of file beo_timing.h.
Referenced by rechteAnpassen().
LogfileLesenDialog* BEO_Timing::logfile [protected]
Definition at line 78 of file beo_timing.h.
Referenced by readLogFile().
HardwareKonfiguration* BEO_Timing::config [protected]
Definition at line 79 of file beo_timing.h.
Referenced by buildConfiguration().
NeuerUserDialog* BEO_Timing::newUser [protected]
Definition at line 80 of file beo_timing.h.
Referenced by neuerUser().
PasswordChangeDialog* BEO_Timing::pwd [protected]
Definition at line 81 of file beo_timing.h.
Referenced by changePwd().
NeuesRennenDialog* BEO_Timing::neu [protected]
Definition at line 82 of file beo_timing.h.
Referenced by NeuesRennen().
Ui::BEO_TimingClass BEO_Timing::ui [private]
Definition at line 91 of file beo_timing.h.
Referenced by BEO_Timing(), CR500_verbinden(), createMenu(), createToolbar(), Read_Race(), setUserRights(), Tree_Build(), and Tree_Settings().
User* BEO_Timing::user [private]
Definition at line 92 of file beo_timing.h.
Referenced by BEO_Timing(), buildConfiguration(), changePwd(), neuerUser(), rechteAnpassen(), setUserRights(), Table_Edit(), and Tree_Build().
QApplication* BEO_Timing::a [private]
Definition at line 93 of file beo_timing.h.
Referenced by createMenu().
RFID_Thread* BEO_Timing::thread [private]
Definition at line 94 of file beo_timing.h.
Referenced by BEO_Timing(), CR500_verbinden(), rfidConnection(), and ~BEO_Timing().
QLabel * BEO_Timing::userLabel [static, private]
Definition at line 100 of file beo_timing.h.
Referenced by createStatusBar(), and updateUserStatus().
QLabel * BEO_Timing::connectionLabel [static, private]
Definition at line 101 of file beo_timing.h.
Referenced by createStatusBar(), and updateRFID().
QLabel * BEO_Timing::messageLabel [static, private]
Definition at line 102 of file beo_timing.h.
Referenced by createStatusBar(), and updateMessage().
QTableView* BEO_Timing::view [private]
Definition at line 103 of file beo_timing.h.
Referenced by exportToCsv(), Read_Race(), and Table_Edit().
QTreeWidget* BEO_Timing::raceTree [private]
Definition at line 104 of file beo_timing.h.
Referenced by Tree_Build(), Tree_Changed(), and Tree_Settings().
Database* BEO_Timing::pMySQL [private]
Definition at line 105 of file beo_timing.h.
Referenced by BEO_Timing(), and checkDB().
DB_Thread* BEO_Timing::pMySQL_thread [private]
Definition at line 106 of file beo_timing.h.
Referenced by BEO_Timing(), checkDB(), mysqlConnection(), and ~BEO_Timing().
QToolBar* BEO_Timing::toolbar [private]
Definition at line 107 of file beo_timing.h.
Referenced by createToolbar().
RFID_CR500* BEO_Timing::pRfid [private]
Definition at line 108 of file beo_timing.h.
Referenced by checkRFID(), CR500_verbinden(), rfidConnection(), and ~BEO_Timing().
bool BEO_Timing::version [private]
Definition at line 109 of file beo_timing.h.
Referenced by BEO_Timing(), and newVersion().
The documentation for this class was generated from the following files:
beo_timing.h
beo_timing.cpp