BEO-Timing: debug/qrc_beo_timing.cpp File Reference
debug/qrc_beo_timing.cpp File Reference
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int
QT_MANGLE_NAMESPACE() qInitResources_beo_timing ()
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_beo_timing)) int QT_MANGLE_NAMESPACE(qCleanupResources_beo_timing)()
Function Documentation
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_beo_timing))
Definition at line 16991 of file qrc_beo_timing.cpp.
References qUnregisterResourceData().
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_beo_timing ()
Definition at line 16984 of file qrc_beo_timing.cpp.
References qRegisterResourceData().
QT_BEGIN_NAMESPACE bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_beo_timing().
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by Q_CONSTRUCTOR_FUNCTION().