BEO-Timing: md5/md5.h File Reference
md5/md5.h File Reference
Diese Funktionen liefern die Moeglichkeit, einen MD5-Hash eines beliebigen String zu generieren.
Classes
struct md5_t
Defines
#define MD5_SIZE 16
#define MAX_MD5_UINT32 ((md5_uint32)4294967295U)
#define MD5_BLOCK_SIZE 64
Typedefs
typedef unsigned int md5_uint32
Functions
void md5_init (md5_t *md5_p)
void md5_process (md5_t *md5_p, const void *buffer, const unsigned int buf_len)
void md5_finish (md5_t *md5_p, void *signature)
void md5_buffer (const char *buffer, const unsigned int buf_len, void *signature)
void md5_sig_to_string (void *signature, char *str, const int str_len)
void md5_sig_from_string (void *signature, const char *str)
Detailed Description
Diese Funktionen liefern die Moeglichkeit, einen MD5-Hash eines beliebigen String zu generieren.
Version:
1.7
Date:
05.03.2006
Author:
Gray Watson
Definition in file md5.h.
Define Documentation
#define MAX_MD5_UINT32 ((md5_uint32)4294967295U)
Definition at line 62 of file md5.h.
Referenced by md5_finish().
#define MD5_BLOCK_SIZE 64
The MD5 algorithm works on blocks of characters of 64 bytes. This is an internal value only and is not necessary for external use.
Definition at line 68 of file md5.h.
Referenced by md5_finish(), and md5_process().
#define MD5_SIZE 16
Size of a standard MD5 signature in bytes. This definition is for external programs only. The MD5 routines themselves reference the signature as 4 unsigned 32-bit integers.
Definition at line 55 of file md5.h.
Referenced by md5_sig_from_string(), and md5_sig_to_string().
Typedef Documentation
typedef unsigned int md5_uint32
NOTE: the following is assumed to generate a 32-bit unsigned data type.
Definition at line 61 of file md5.h.
Function Documentation
void md5_buffer (const char * buffer, const unsigned int buf_len, void * signature)
DESCRIPTION:
This function is used to calculate a MD5 signature for a buffer of bytes. If you only have part of a buffer that you want to process then md5_init, md5_process, and md5_finish should be used.
Returns:
None.
Parameters:
buffer A buffer of bytes whose MD5 signature we are calculating.
buf_len The length of the buffer.
signature A 16 byte buffer that will contain the MD5 signature.
Definition at line 483 of file md5.cpp.
References md5_finish(), md5_init(), and md5_process().
Referenced by LogonDialog::on_LogonButton_released(), RechteAnpassen::on_okButton_released(), PasswordChangeDialog::on_okButton_released(), and NeuerUserDialog::on_okButton_released().
void md5_finish (md5_t * md5_p, void * signature)
DESCRIPTION:
Finish a progressing MD5 calculation and copy the resulting MD5 signature into the result buffer which should be 16 bytes (MD5_SIZE). After this call, the MD5 structure is invalid.
Returns:
None.
Parameters:
md5_p Pointer to MD5 structure which we are finishing.
signature A 16 byte buffer that will contain the MD5 signature.
Definition at line 399 of file md5.cpp.
References MAX_MD5_UINT32, MD5_BLOCK_SIZE, md5_t::md_buf_len, md5_t::md_buffer, and md5_t::md_total.
Referenced by md5_buffer().
void md5_init (md5_t * md5_p)
DESCRIPTION:
Initialize structure containing state of MD5 computation. (RFC 1321, 3.3: Step 3). This is for progressive MD5 calculations only. If you have the complete string available, md5_buffer should be used. md5_process should be called for each bunch of bytes and after the last process call, md5_finish should be called to get the signature.
Returns:
None.
Parameters:
md5_p Pointer to md5 structure that we are initializing.
Definition at line 294 of file md5.cpp.
References md5_t::md_A, md5_t::md_B, md5_t::md_buf_len, md5_t::md_C, md5_t::md_D, and md5_t::md_total.
Referenced by md5_buffer(), and LogonDialog::on_LogonButton_released().
void md5_process (md5_t * md5_p, const void * buffer, const unsigned int buf_len)
DESCRIPTION:
This function is used to progressively calculate a MD5 signature some number of bytes at a time. If you have the complete string available, md5_buffer should be used. The MD5 structure should have been initialized with md5_init and after the last process call, md5_finish should be called to get the results.
Returns:
None.
Parameters:
md5_p Pointer to MD5 structure which we are progressively updating.
buffer A buffer of bytes whose MD5 signature we are calculating.
buf_len The length of the buffer.
Definition at line 329 of file md5.cpp.
References BLOCK_SIZE_MASK, MD5_BLOCK_SIZE, md5_t::md_buf_len, and md5_t::md_buffer.
Referenced by md5_buffer().
void md5_sig_from_string (void * signature, const char * str)
DESCRIPTION:
Convert a MD5 signature from a hexadecimal string representation into a 16 byte buffer.
Returns:
None.
Parameters:
signature A 16 byte buffer that will contain the MD5 signature.
str A string of charactes which _must_ be at least 32 bytes long (2 characters per MD5 byte).
Definition at line 565 of file md5.cpp.
References HEX_STRING, and MD5_SIZE.
void md5_sig_to_string (void * signature, char * str, const int str_len)
DESCRIPTION:
Convert a MD5 signature in a 16 byte buffer into a hexadecimal string representation.
Returns:
None.
Parameters:
signature a 16 byte buffer that contains the MD5 signature.
str a string of charactes which should be at least 33 bytes long (2 characters per MD5 byte and 1 for the NULL).
str_len the length of the string.
Definition at line 519 of file md5.cpp.
References HEX_STRING, and MD5_SIZE.